//! Shared metadata contract for capture fixtures and replay lanes.

use std::path::Path;

use serde::{Deserialize, Serialize};

/// High-level intent of a capture fixture.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CaptureKind {
    /// Device left untouched at rest.
    Idle,
    /// One or more analog axes swept through their range.
    Sweep,
    /// Buttons, hats, encoders, or other controls exercised.
    Controls,
    /// Pedal axes exercised.
    Pedals,
    /// Handbrake axis exercised.
    Handbrake,
}

/// Provenance class for capture fixture evidence.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CaptureEvidenceSource {
    /// Captured from physical hardware.
    Real,
    /// Produced by a virtual device backend.
    Virtual,
    /// Generated by test fixtures or property tests.
    Synthetic,
}

impl CaptureEvidenceSource {
    #[must_use]
    pub const fn can_validate_real_hardware(self) -> bool {
        matches!(self, Self::Real)
    }
}

/// Shared fixture metadata for HID capture replay.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CaptureFixtureMetadata {
    vendor_id: String,
    product_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    interface_number: Option<u8>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    usage_page: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    usage: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    report_descriptor_crc32: Option<String>,
    capture_kind: CaptureKind,
    hardware_source: CaptureEvidenceSource,
    real_hardware_validated: bool,
}

impl CaptureFixtureMetadata {
    /// Create fixture metadata from numeric USB identity values.
    #[must_use]
    pub fn new(
        vendor_id: u16,
        product_id: u16,
        capture_kind: CaptureKind,
        hardware_source: CaptureEvidenceSource,
    ) -> Self {
        Self {
            vendor_id: hex_u16(vendor_id),
            product_id: hex_u16(product_id),
            interface_number: None,
            usage_page: None,
            usage: None,
            report_descriptor_crc32: None,
            capture_kind,
            hardware_source,
            real_hardware_validated: false,
        }
    }

    /// Create fixture metadata from preformatted hex strings.
    pub fn from_hex_ids(
        vendor_id: impl Into<String>,
        product_id: impl Into<String>,
        capture_kind: CaptureKind,
        hardware_source: CaptureEvidenceSource,
    ) -> Result<Self, CaptureFixtureMetadataError> {
        let metadata = Self {
            vendor_id: vendor_id.into(),
            product_id: product_id.into(),
            interface_number: None,
            usage_page: None,
            usage: None,
            report_descriptor_crc32: None,
            capture_kind,
            hardware_source,
            real_hardware_validated: false,
        };
        metadata.validate()?;
        Ok(metadata)
    }

    #[must_use]
    pub fn with_interface_number(mut self, interface_number: u8) -> Self {
        self.interface_number = Some(interface_number);
        self
    }

    pub fn with_usage_page(
        mut self,
        usage_page: impl Into<String>,
    ) -> Result<Self, CaptureFixtureMetadataError> {
        self.usage_page = Some(non_empty_string("usage_page", usage_page)?);
        Ok(self)
    }

    pub fn with_usage(
        mut self,
        usage: impl Into<String>,
    ) -> Result<Self, CaptureFixtureMetadataError> {
        self.usage = Some(non_empty_string("usage", usage)?);
        Ok(self)
    }

    pub fn with_report_descriptor_crc32(
        mut self,
        report_descriptor_crc32: impl Into<String>,
    ) -> Result<Self, CaptureFixtureMetadataError> {
        self.report_descriptor_crc32 = Some(non_empty_string(
            "report_descriptor_crc32",
            report_descriptor_crc32,
        )?);
        self.validate()?;
        Ok(self)
    }

    pub fn with_real_hardware_validated(
        mut self,
        real_hardware_validated: bool,
    ) -> Result<Self, CaptureFixtureMetadataError> {
        self.real_hardware_validated = real_hardware_validated;
        self.validate()?;
        Ok(self)
    }

    pub fn validate(&self) -> Result<(), CaptureFixtureMetadataError> {
        validate_hex_u16("vendor_id", &self.vendor_id)?;
        validate_hex_u16("product_id", &self.product_id)?;
        if let Some(usage_page) = &self.usage_page {
            validate_hex_string("usage_page", usage_page)?;
        }
        if let Some(usage) = &self.usage {
            validate_hex_string("usage", usage)?;
        }
        if let Some(crc32) = &self.report_descriptor_crc32 {
            validate_hex_crc32("report_descriptor_crc32", crc32)?;
        }
        if self.real_hardware_validated && !self.hardware_source.can_validate_real_hardware() {
            return Err(CaptureFixtureMetadataError::NonRealMarkedValidated {
                hardware_source: self.hardware_source,
            });
        }
        Ok(())
    }

    pub fn validate_artifact_path(
        &self,
        path: impl AsRef<Path>,
    ) -> Result<(), CaptureFixtureMetadataError> {
        self.validate()?;
        let normalized = path.as_ref().to_string_lossy().replace('\\', "/");
        if self.hardware_source != CaptureEvidenceSource::Real
            && normalized.starts_with("ci/hardware/")
        {
            return Err(CaptureFixtureMetadataError::NonRealUnderHardwareLane { path: normalized });
        }
        Ok(())
    }

    #[must_use]
    pub fn vendor_id(&self) -> &str {
        &self.vendor_id
    }

    #[must_use]
    pub fn product_id(&self) -> &str {
        &self.product_id
    }

    #[must_use]
    pub const fn interface_number(&self) -> Option<u8> {
        self.interface_number
    }

    #[must_use]
    pub fn usage_page(&self) -> Option<&str> {
        self.usage_page.as_deref()
    }

    #[must_use]
    pub fn usage(&self) -> Option<&str> {
        self.usage.as_deref()
    }

    #[must_use]
    pub fn report_descriptor_crc32(&self) -> Option<&str> {
        self.report_descriptor_crc32.as_deref()
    }

    #[must_use]
    pub const fn capture_kind(&self) -> CaptureKind {
        self.capture_kind
    }

    #[must_use]
    pub const fn hardware_source(&self) -> CaptureEvidenceSource {
        self.hardware_source
    }

    #[must_use]
    pub const fn real_hardware_validated(&self) -> bool {
        self.real_hardware_validated
    }

    #[must_use]
    pub const fn is_real_hardware_evidence(&self) -> bool {
        self.real_hardware_validated && matches!(self.hardware_source, CaptureEvidenceSource::Real)
    }
}

/// Errors produced while validating capture fixture metadata.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum CaptureFixtureMetadataError {
    #[error("{field} must not be empty")]
    EmptyField { field: &'static str },
    #[error("{field} must be uppercase 0x-prefixed hex, got {value}")]
    InvalidHex { field: &'static str, value: String },
    #[error("non-real source {hardware_source:?} cannot set real_hardware_validated=true")]
    NonRealMarkedValidated {
        hardware_source: CaptureEvidenceSource,
    },
    #[error("non-real capture fixture must not be stored under ci/hardware: {path}")]
    NonRealUnderHardwareLane { path: String },
}

fn hex_u16(value: u16) -> String {
    format!("0x{value:04X}")
}

fn non_empty_string(
    field: &'static str,
    value: impl Into<String>,
) -> Result<String, CaptureFixtureMetadataError> {
    let value = value.into();
    if value.trim().is_empty() {
        Err(CaptureFixtureMetadataError::EmptyField { field })
    } else {
        Ok(value)
    }
}

fn validate_hex_u16(field: &'static str, value: &str) -> Result<(), CaptureFixtureMetadataError> {
    if value.len() == 6 && value.starts_with("0x") && is_upper_hex(&value[2..]) {
        return Ok(());
    }
    Err(CaptureFixtureMetadataError::InvalidHex {
        field,
        value: value.to_owned(),
    })
}

fn validate_hex_crc32(field: &'static str, value: &str) -> Result<(), CaptureFixtureMetadataError> {
    if value.len() == 10 && value.starts_with("0x") && is_upper_hex(&value[2..]) {
        return Ok(());
    }
    Err(CaptureFixtureMetadataError::InvalidHex {
        field,
        value: value.to_owned(),
    })
}

fn validate_hex_string(
    field: &'static str,
    value: &str,
) -> Result<(), CaptureFixtureMetadataError> {
    if value.len() > 2 && value.starts_with("0x") && is_upper_hex(&value[2..]) {
        return Ok(());
    }
    Err(CaptureFixtureMetadataError::InvalidHex {
        field,
        value: value.to_owned(),
    })
}

fn is_upper_hex(value: &str) -> bool {
    !value.is_empty()
        && value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'A'..=b'F').contains(&byte))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn numeric_constructor_formats_hex_ids() -> Result<(), CaptureFixtureMetadataError> {
        let metadata = CaptureFixtureMetadata::new(
            0x346E,
            0x0014,
            CaptureKind::Idle,
            CaptureEvidenceSource::Real,
        )
        .with_interface_number(0)
        .with_usage_page("0xFF00")?
        .with_usage("0x0001")?
        .with_report_descriptor_crc32("0xD8079D85")?
        .with_real_hardware_validated(true)?;

        assert_eq!(metadata.vendor_id(), "0x346E");
        assert_eq!(metadata.product_id(), "0x0014");
        assert_eq!(metadata.interface_number(), Some(0));
        assert_eq!(metadata.capture_kind(), CaptureKind::Idle);
        assert!(metadata.is_real_hardware_evidence());
        metadata.validate_artifact_path("ci/hardware/moza-r5/2026-05-10/captures/r5-idle.jsonl")
    }

    #[test]
    fn virtual_metadata_cannot_claim_real_validation() {
        let result = CaptureFixtureMetadata::new(
            0x346E,
            0x0014,
            CaptureKind::Sweep,
            CaptureEvidenceSource::Virtual,
        )
        .with_real_hardware_validated(true);

        assert_eq!(
            result,
            Err(CaptureFixtureMetadataError::NonRealMarkedValidated {
                hardware_source: CaptureEvidenceSource::Virtual,
            })
        );
    }

    #[test]
    fn synthetic_metadata_is_blocked_from_hardware_lane_paths() {
        let metadata = CaptureFixtureMetadata::new(
            0x346E,
            0x0014,
            CaptureKind::Controls,
            CaptureEvidenceSource::Synthetic,
        );

        assert_eq!(
            metadata.validate_artifact_path("ci/hardware/moza-r5/2026-05-10/captures/ks.jsonl"),
            Err(CaptureFixtureMetadataError::NonRealUnderHardwareLane {
                path: "ci/hardware/moza-r5/2026-05-10/captures/ks.jsonl".to_owned(),
            })
        );
        assert!(
            metadata
                .validate_artifact_path("crates/hid-moza-protocol/fixtures/ks.jsonl")
                .is_ok()
        );
    }

    #[test]
    fn lowercase_hex_is_rejected() {
        assert_eq!(
            CaptureFixtureMetadata::from_hex_ids(
                "0x346e",
                "0x0014",
                CaptureKind::Pedals,
                CaptureEvidenceSource::Real,
            ),
            Err(CaptureFixtureMetadataError::InvalidHex {
                field: "vendor_id",
                value: "0x346e".to_owned(),
            })
        );
    }

    #[test]
    fn serde_uses_expected_contract_names() -> Result<(), Box<dyn std::error::Error>> {
        let metadata = CaptureFixtureMetadata::new(
            0x346E,
            0x0014,
            CaptureKind::Handbrake,
            CaptureEvidenceSource::Virtual,
        )
        .with_report_descriptor_crc32("0xD8079D85")?;

        let json = serde_json::to_string(&metadata)?;
        assert!(json.contains("\"vendor_id\":\"0x346E\""));
        assert!(json.contains("\"product_id\":\"0x0014\""));
        assert!(json.contains("\"capture_kind\":\"handbrake\""));
        assert!(json.contains("\"hardware_source\":\"virtual\""));
        assert!(json.contains("\"real_hardware_validated\":false"));
        Ok(())
    }
}
