use super::{ConfigWriterFactory, constructors::*};

/// Returns the canonical config writer registry for all supported integrations.
pub fn config_writer_factories() -> &'static [(&'static str, ConfigWriterFactory)] {
    &[
        ("iracing", new_iracing_config_writer),
        ("acc", new_acc_config_writer),
        ("acc2", new_acc2_config_writer),
        ("ac_evo", new_ac_evo_config_writer),
        ("ac_rally", new_ac_rally_config_writer),
        ("ams2", new_ams2_config_writer),
        ("rfactor2", new_rfactor2_config_writer),
        ("eawrc", new_eawrc_config_writer),
        ("f1", new_f1_config_writer),
        ("f1_25", new_f1_25_config_writer),
        ("f1_native", new_f1_native_config_writer),
        ("dirt5", new_dirt5_config_writer),
        ("dirt_rally_2", new_dirt_rally_2_config_writer),
        ("rbr", new_rbr_config_writer),
        ("gran_turismo_7", new_gran_turismo_7_config_writer),
        ("gran_turismo_sport", new_gran_turismo_sport_config_writer),
        ("f1_manager", new_f1_manager_config_writer),
        ("assetto_corsa", new_assetto_corsa_config_writer),
        ("forza_motorsport", new_forza_motorsport_config_writer),
        ("forza_horizon_4", new_forza_horizon_4_config_writer),
        ("forza_horizon_5", new_forza_horizon_5_config_writer),
        ("beamng_drive", new_beamng_drive_config_writer),
        ("project_cars_2", new_project_cars_2_config_writer),
        ("project_cars_3", new_project_cars_3_config_writer),
        ("live_for_speed", new_live_for_speed_config_writer),
        ("wrc_generations", new_wrc_generations_config_writer),
        ("wrc_9", new_wrc_9_config_writer),
        ("wrc_10", new_wrc_10_config_writer),
        ("v_rally_4", new_v_rally_4_config_writer),
        ("dirt_showdown", new_dirt_showdown_config_writer),
        ("dirt4", new_dirt4_config_writer),
        ("ets2", new_ets2_config_writer),
        ("ats", new_ats_config_writer),
        ("wreckfest", new_wreckfest_config_writer),
        ("flatout", new_flatout_config_writer),
        ("dakar_desert_rally", new_dakar_config_writer),
        ("rennsport", new_rennsport_config_writer),
        ("raceroom", new_raceroom_config_writer),
        ("kartkraft", new_kartkraft_config_writer),
        ("grid_autosport", new_grid_autosport_config_writer),
        ("grid_2019", new_grid_2019_config_writer),
        ("grid_legends", new_grid_legends_config_writer),
        ("dirt3", new_dirt3_config_writer),
        ("race_driver_grid", new_race_driver_grid_config_writer),
        ("automobilista", new_automobilista_config_writer),
        ("nascar", new_nascar_config_writer),
        ("nascar_21", new_nascar_21_config_writer),
        ("le_mans_ultimate", new_le_mans_ultimate_config_writer),
        ("wtcr", new_wtcr_config_writer),
        ("trackmania", new_trackmania_config_writer),
        ("simhub", new_simhub_config_writer),
        ("gravel", new_gravel_config_writer),
        ("seb_loeb_rally", new_seb_loeb_rally_config_writer),
        ("mudrunner", new_mudrunner_config_writer),
        ("snowrunner", new_snowrunner_config_writer),
        ("motogp", new_motogp_config_writer),
        ("ride5", new_ride5_config_writer),
        ("rfactor1", new_rfactor1_config_writer),
        ("gtr2", new_gtr2_config_writer),
        ("race_07", new_race_07_config_writer),
        ("gsc", new_gsc_config_writer),
    ]
}
