//! Configuration writers for game-specific telemetry setup

#![deny(static_mut_refs)]

mod path;
mod registry;
mod types;
mod writers;

pub use registry::{ConfigWriterFactory, config_writer_factories};
pub use types::{ConfigDiff, ConfigWriter, DiffOperation, TelemetryConfig};
pub use writers::{
    ACC2ConfigWriter,
    ACCConfigWriter,
    ACEvoConfigWriter,
    ACRallyConfigWriter,
    AMS2ConfigWriter,
    AssettoCorsaConfigWriter,
    AtsConfigWriter,
    AutomobilistaConfigWriter,
    BeamNGDriveConfigWriter,
    DakarDesertRallyConfigWriter,
    Dirt3ConfigWriter,
    Dirt4ConfigWriter,
    Dirt5ConfigWriter,
    DirtRally2ConfigWriter,
    DirtShowdownConfigWriter,
    EAWRCConfigWriter,
    Ets2ConfigWriter,
    F1ConfigWriter,
    F1ManagerConfigWriter,
    F1NativeConfigWriter,
    F1_25ConfigWriter,
    FlatOutConfigWriter,
    ForzaHorizon4ConfigWriter,
    ForzaHorizon5ConfigWriter,
    ForzaMotorsportConfigWriter,
    GranTurismo7ConfigWriter,
    GranTurismo7SportsConfigWriter,
    GravelConfigWriter,
    Grid2019ConfigWriter,
    GridAutosportConfigWriter,
    GridLegendsConfigWriter,
    IRacingConfigWriter,
    KartKraftConfigWriter,
    LFSConfigWriter,
    LeMansUltimateConfigWriter,
    MotoGPConfigWriter,
    MudRunnerConfigWriter,
    Nascar21ConfigWriter,
    NascarConfigWriter,
    PCars2ConfigWriter,
    PCars3ConfigWriter,
    RBRConfigWriter,
    RFactor1ConfigWriter,
    RFactor2ConfigWriter,
    RaceDriverGridConfigWriter,
    RaceRoomConfigWriter,
    RennsportConfigWriter,
    Ride5ConfigWriter,
    SebLoebRallyConfigWriter,
    SimHubConfigWriter,
    SnowRunnerConfigWriter,
    TrackmaniaConfigWriter,
    VRally4ConfigWriter,
    WrcGenerationsConfigWriter,
    WrcKylotonnConfigWriter,
    WrcKylotonnVariant,
    WreckfestConfigWriter,
    WtcrConfigWriter,
};
